version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - ".:/var/www/html/"
    ports:
      - "127.0.0.1:80:80"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hackme
    volumes:
      - ./mysql-charset.cnf:/etc/mysql/conf.d/charset.cnf:ro
      - ./mysql-password.cnf:/etc/mysql/conf.d/password.cnf:ro
